version: '3.4'
services:
  conda_build:
    image: brownccv/jh_sandbox:0.1.1
    user: root
    volumes:
      - ./requirements:/tmp
    command: > 
      bash -c "
      conda create --name ${CLASS} python=3.8 &&
      conda install -y --name ${CLASS} -c conda-forge --file /tmp/classes/${CLASS}/requirements.txt &&
      source activate ${CLASS} &&
      pip install -r /tmp/classes/${CLASS}/requirements.pip.txt &&
      conda env export --name ${CLASS} > /tmp/out/environment.yml &&
      conda env export --name ${CLASS} --no-build > /tmp/out/environment.nb.yml
      "
    environment: 
      - CLASS=${CLASS}

  julia_build:
    image: julia:1.5-buster
    volumes:
      - ./requirements/classes/${CLASS}:/tmp/env/
      - ./scripts:/tmp/scripts/
    working_dir: /tmp/env
    command: >
      bash -c "julia -e 'import Pkg; Pkg.activate(\"julia_env\"); 
      include(expanduser(\"/tmp/scripts/install_julia_packages.jl\"));
      include(expanduser(\"/tmp/env/requirements.jl\"));
      install(julia_packages);
      '"

  jh_image: &jh_image
    build:
      context: .
      target: ${TARGET}
      cache_from: 
        - gcr.io/jupyterhub-docker-images/${CLASS}:latest
      args: 
        CLASS: ${CLASS}
        WITH_MYSQL: ${WITH_MYSQL}