version: '3.4'
services:
  conda_build:
    image: brownccv/jh_sandbox:0.1.0
    volumes:
      - ./${CLASS}:/tmp/
    command: > 
      bash -c "conda create --name ${CLASS} python=3.8 &&
      sudo conda install -y --name ${CLASS} -c conda-forge --file /tmp/requirements.txt &&
      sudo conda env export --name ${CLASS} > /tmp/environment.yml &&
      sudo conda env export --name ${CLASS} --no-build > /tmp/environment.nb.yml
      "
  jh_image:
    build:
      context: .
      args: 
        CLASS: ${CLASS}
    image: gcr.io/jupyterhub-docker-images/${CLASS}