name: Build Image for ${CLASS}
on: 
  push:
      paths:
      - 'requirements/classes/${CLASS}/**'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'scripts/**'
      - '.github/workflows/${CLASS}.yml'

env:
  CLASS: ${CLASS}
  TARGET: ${TARGET}
  SQLITE: ${SQLITE}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Up GCloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID_JH_DOCKER }}
          service_account_key: ${{ secrets.GCP_SA_KEY_JH_DOCKER }}
          export_default_credentials: true

      - name: Create Julia Environment Files
        run: |
          sudo --preserve-env=CLASS docker-compose up julia_build

      - name: Configure Docker
        run: gcloud auth configure-docker
      - name: Build and Push JH Image
        run: |
          COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose up jh_image
          docker tag jupyterhub-docker-images_jh_image:latest gcr.io/jupyterhub-docker-images/${CLASS}:${GITHUB_REF##*/}
          docker tag jupyterhub-docker-images_jh_image:latest gcr.io/jupyterhub-docker-images/${CLASS}:latest
          docker push gcr.io/jupyterhub-docker-images/${CLASS}:latest
          docker push gcr.io/jupyterhub-docker-images/${CLASS}:${GITHUB_REF##*/}
