name: Tag Fall Production Image for apma0360
on: [workflow_dispatch]


env:
  CLASS: apma0360
  TARGET: base
  SEASON: fall
  YEAR: '2020'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: Set Up GCloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID_JH_DOCKER }}
          service_account_key: ${{ secrets.GCP_SA_KEY_JH_DOCKER }}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and Push JH Image
        run: |
          COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose up jh_image
          docker tag jupyterhub-docker-images_jh_image:latest gcr.io/jupyterhub-docker-images/${CLASS}:${GITHUB_REF##*/}
          docker tag jupyterhub-docker-images_jh_image:latest gcr.io/jupyterhub-docker-images/${CLASS}:${GITHUB_SHA}
          docker tag jupyterhub-docker-images_jh_image:latest gcr.io/jupyterhub-docker-images/${CLASS}:latest
          docker tag jupyterhub-docker-images_jh_image:latest gcr.io/jupyterhub-docker-images/${CLASS}:${SEASON}-${YEAR}
          docker push gcr.io/jupyterhub-docker-images/${CLASS}:latest
          docker push gcr.io/jupyterhub-docker-images/${CLASS}:${SEASON}-${YEAR}
          docker push gcr.io/jupyterhub-docker-images/${CLASS}:${GITHUB_REF##*/}
          docker push gcr.io/jupyterhub-docker-images/${CLASS}:${GITHUB_SHA}

      - name: Upload Conda Env Files
          uses: actions/upload-artifact@v2
          with:
            name: conda-environment-files
            path: requirements/out