name: Build and Publish Docker Image
on: 
  push:
    paths:
      - 'apma0360/**'
      - 'Dokerfile'
      - 'docker-compose.yml'
      - 'scripts/**'
      - '.github/**'
jobs:
  apma0360:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.4
      - name: Create Environment Files
        run: |
          sudo --preserve-env=CLASS docker-compose up conda_build
        env:
          CLASS: apma0360
      - uses: actions/upload-artifact@v2
        with:
          name: conda-environment-files
          path: apma0360
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID_JH_DOCKER }}
          service_account_key: ${{ secrets.GCP_SA_KEY_JH_DOCKER }}
          export_default_credentials: true
      - name: Configure Docker
        run: gcloud auth configure-docker
      - name: Build and Push APMA0360 image
        run: |
          docker-compose build jh_image
          docker-compose push jh_image
        env:
          CLASS: apma0360
