name: Build Image for data1010
on: 
  push:
      paths:
      - 'requirements/classes/data1010/**'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'scripts/**'
      - '.github/workflows/data1010.yml'

env:
  CLASS: data1010
  TARGET: r_julia

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Julia Environment Files
        run: |
          sudo --preserve-env=CLASS docker-compose up julia_build
      - name: Upload Julia Env Files
        uses: actions/upload-artifact@v2
        with:
          name: julia-environment-files
          path: requirements/classes/${{ env.CLASS }}/julia_env

      - name: Set Up GCloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID_JH_DOCKER }}
          service_account_key: ${{ secrets.GCP_SA_KEY_JH_DOCKER }}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker
      - name: Build and Push JH Image
        run: |
          COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose up jh_image
          docker tag jupyterhub-docker-images_jh_image:latest gcr.io/jupyterhub-docker-images/data1010:${GITHUB_REF##*/}
          docker tag jupyterhub-docker-images_jh_image:latest gcr.io/jupyterhub-docker-images/data1010:${GITHUB_SHA}
          docker tag jupyterhub-docker-images_jh_image:latest gcr.io/jupyterhub-docker-images/data1010:latest
          docker push gcr.io/jupyterhub-docker-images/data1010:latest
          docker push gcr.io/jupyterhub-docker-images/data1010:${GITHUB_REF##*/}
          docker push gcr.io/jupyterhub-docker-images/data1010:${GITHUB_SHA}